### PR TITLE
SecQuery::FilingDetail

### PR DESCRIPTION
**Pull request by david-christensen**
- Adding `SecQuery::FilingDetail` for parsing the "Filing Detail" EDGAR page of a filing.
- Adding the `.detail` method to `SecQuery::Filing` instances.

### CODE REVIEW

**Comment by tyrauber** [comment]
Hi @david-christensen, Is there a reason FilingDetail needs to be a different class as opposed to expanding the parsing of filing to include the additional details?  I guess because it requires a second request to get additional data, and that extra data might not always be required?  Would you also mind updating the documentation to reflect the additional functionality?

**Comment by david-christensen** [comment]
Hi @tyrauber , yeah I definitely did not want to make it required. I was also seeing that the filings queries seemed to be browsing the EDGAR Search results page such as this one:
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193&owner=exclude&count=40&hidefilings=0
and that clicking on a "document" link leads to a "Filing Detail" page:
https://www.sec.gov/cgi-bin/browse-edgar?action=getcompany&CIK=0000320193&owner=exclude&count=40&hidefilings=0

Having the logic separate for fetching and parsing what EDGAR calls "Filing Detail" just made sense to me after becoming a little familiar with their pages.

I also like to keep the class size smaller so it's not so unwieldy.
Thoughts?

**Comment by david-christensen** [comment]
Also, I'll try to add some documentation.

**Comment by tyrauber** [comment]
@david-christensen Thanks for the documentation. That all makes sense.  My only question now is usage. It looks like the only way to retrieve the FilingDetail is by manually fetching it. What about adding a convenience method `detail` on filing to easily fetch the FilingDetail for any filing?

Something like:
`SecQuery::Entity.find("Apple, Inc.").filings.first.detail`

**Comment by david-christensen** [comment]
@tyrauber I actually did that already... but it's not cached, I'll make that update.

**Comment by david-christensen** [comment]
I also added that to the documentation for `SecQuery::Filing`, fwiw.

**Comment by tyrauber** [comment]
@david-christensen, you absolutely did! On first commit.  My apologies.  Thanks for the awesome contribution.   LGTM. Merged.

**Comment by david-christensen** [comment]
@tyrauber Absolutely and no worries! Thank you for reviewing!

**Pull request merged**
