### PR TITLE
Adding SecQuery::Document::Form4 class

### PR DESCRIPTION
**Pull request by david-christensen**
Changes here are meant to serve as a starting point for adding Documents to the project. I add `Form4` as a very basic example. 

See tests for example usage.

### CODE REVIEW

**Comment by tyrauber** [comment]
Hi @david-christensen, thanks for the functionality and spec coverage. Would you mind updating documentation also?

**Comment by tyrauber** [comment]
@david-christensen . I merged in the FilingDetail PR. If you could you rebase off master and add some documentation, I'll merge this one in as well and push a release.

**Comment by david-christensen** [comment]
@tyrauber You bet! Now that the FilingDetail PR is merged, I might expand on changes here, in order to make them more useful! Thanks for the feedback thus far!

**Comment by david-christensen** [comment]
@tyrauber When you've got a minute for another look, here - the branch is now up-to-date with master and I've added to the documentation. Let me know if that'll work for now. Thanks!

**Pull request closed without merging**
